package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1



/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private int id;
     private Matricula matricula;
     private Modulo modulo;
     private Character estado;
     private String observacion;

    public Asistencia() {
    }

	
    public Asistencia(int id, Matricula matricula, Modulo modulo) {
        this.id = id;
        this.matricula = matricula;
        this.modulo = modulo;
    }
    public Asistencia(int id, Matricula matricula, Modulo modulo, Character estado, String observacion) {
       this.id = id;
       this.matricula = matricula;
       this.modulo = modulo;
       this.estado = estado;
       this.observacion = observacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


