package Pojo;
// Generated 02-nov-2016 10:39:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Canton generated by hbm2java
 */
public class Canton  implements java.io.Serializable {


     private int id;
     private Provincia provincia;
     private String descripcion;
     private String codigo;
     private Set parroquias = new HashSet(0);

    public Canton() {
    }

	
    public Canton(int id, Provincia provincia) {
        this.id = id;
        this.provincia = provincia;
    }
    public Canton(int id, Provincia provincia, String descripcion, String codigo, Set parroquias) {
       this.id = id;
       this.provincia = provincia;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.parroquias = parroquias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getParroquias() {
        return this.parroquias;
    }
    
    public void setParroquias(Set parroquias) {
        this.parroquias = parroquias;
    }




}


