package Pojo;
// Generated 30-oct-2016 21:58:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int id;
     private Seccion seccion;
     private String descripcion;
     private String paralelo;
     private Character estado;
     private Set modulos = new HashSet(0);
     private Set solicitudInscripcions = new HashSet(0);
     private Set precios = new HashSet(0);

    public Curso() {
    }

	
    public Curso(int id, Seccion seccion) {
        this.id = id;
        this.seccion = seccion;
    }
    public Curso(int id, Seccion seccion, String descripcion, String paralelo, Character estado, Set modulos, Set solicitudInscripcions, Set precios) {
       this.id = id;
       this.seccion = seccion;
       this.descripcion = descripcion;
       this.paralelo = paralelo;
       this.estado = estado;
       this.modulos = modulos;
       this.solicitudInscripcions = solicitudInscripcions;
       this.precios = precios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Seccion getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(Seccion seccion) {
        this.seccion = seccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getParalelo() {
        return this.paralelo;
    }
    
    public void setParalelo(String paralelo) {
        this.paralelo = paralelo;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }
    public Set getSolicitudInscripcions() {
        return this.solicitudInscripcions;
    }
    
    public void setSolicitudInscripcions(Set solicitudInscripcions) {
        this.solicitudInscripcions = solicitudInscripcions;
    }

    public Character getEstado() {
        return estado;
    }

    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Set precios) {
        this.precios = precios;
    }



}


