package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1



/**
 * DatosLab generated by hbm2java
 */
public class DatosLab  implements java.io.Serializable {


     private int id;
     private Estudiante estudiante;
     private Parroquia parroquia;
     private String empresa;
     private String direccion;
     private String telefono;
     private String email;
     private String cargo;

    public DatosLab() {
    }

	
    public DatosLab(int id) {
        this.id = id;
    }
    public DatosLab(int id, Estudiante estudiante, Parroquia parroquia, String empresa, String direccion, String telefono, String email, String cargo) {
       this.id = id;
       this.estudiante = estudiante;
       this.parroquia = parroquia;
       this.empresa = empresa;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.cargo = cargo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Parroquia getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(Parroquia parroquia) {
        this.parroquia = parroquia;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }




}


