package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1



/**
 * DatosDom generated by hbm2java
 */
public class DatosDom  implements java.io.Serializable {


     private int id;
     private Estudiante estudiante;
     private Parroquia parroquia;
     private String direccion;
     private String telefono;

    public DatosDom() {
    }

	
    public DatosDom(int id) {
        this.id = id;
    }
    public DatosDom(int id, Estudiante estudiante, Parroquia parroquia, String direccion, String telefono) {
       this.id = id;
       this.estudiante = estudiante;
       this.parroquia = parroquia;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Parroquia getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(Parroquia parroquia) {
        this.parroquia = parroquia;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


