package Pojo;
// Generated 11/04/2016 15:34:25 by Hibernate Tools 4.3.1



/**
 * DetalleTribunal generated by hbm2java
 */
public class DetalleTribunal  implements java.io.Serializable {


     private int id;
     private TipoTribunal tipoTribunal;
     private Tribunal tribunal;

    public DetalleTribunal() {
    }

	
    public DetalleTribunal(int id) {
        this.id = id;
    }
    public DetalleTribunal(int id, TipoTribunal tipoTribunal, Tribunal tribunal) {
       this.id = id;
       this.tipoTribunal = tipoTribunal;
       this.tribunal = tribunal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoTribunal getTipoTribunal() {
        return this.tipoTribunal;
    }
    
    public void setTipoTribunal(TipoTribunal tipoTribunal) {
        this.tipoTribunal = tipoTribunal;
    }
    public Tribunal getTribunal() {
        return this.tribunal;
    }
    
    public void setTribunal(Tribunal tribunal) {
        this.tribunal = tribunal;
    }




}


