package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int id;
     private String cedPasaporte;
     private String nombres;
     private String apellidos;
     private String email;
     private String celular;
     private Date fechaNac;
     private Character sexo;
     private Character estadoCivil;
     private Character etnia;
     private String paisOrigen;
     private Integer dscColegiatura;
     private Set datosDoms = new HashSet(0);
     private Set datosNacs = new HashSet(0);
     private Set datosLabs = new HashSet(0);
     private Set solicitudInscripcions = new HashSet(0);
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private Set titulos = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(int id, String cedPasaporte) {
        this.id = id;
        this.cedPasaporte = cedPasaporte;
    }
    public Estudiante(int id, String cedPasaporte, String nombres, String apellidos, String email, String celular, Date fechaNac, Character sexo, Character estadoCivil, String paisOrigen, Integer dscColegiatura, Set datosDoms, Set datosNacs, Set datosLabs, Set solicitudInscripcions,Character etnia,String primerNombre,String segundoNombre,String primerApellido,String segundoApellido,Set titulos) {
       this.id = id;
       this.cedPasaporte = cedPasaporte;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.celular = celular;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.paisOrigen = paisOrigen;
       this.dscColegiatura = dscColegiatura;
       this.datosDoms = datosDoms;
       this.datosNacs = datosNacs;
       this.datosLabs = datosLabs;
       this.solicitudInscripcions = solicitudInscripcions;
       this.etnia = etnia;
       this.primerNombre=primerNombre;
       this.segundoNombre=segundoNombre;
       this.primerApellido=primerApellido;
       this.segundoApellido=segundoApellido;
       this.titulos=titulos;
    }

    public Set getTitulos() {
        return titulos;
    }

    public void setTitulos(Set titulos) {
        this.titulos = titulos;
    }

    public String getPrimerNombre() {
        return primerNombre;
    }

    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    public String getSegundoNombre() {
        return segundoNombre;
    }

    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    public String getPrimerApellido() {
        return primerApellido;
    }

    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    public String getSegundoApellido() {
        return segundoApellido;
    }

    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }    

    public Character getEtnia() {
        return etnia;
    }

    public void setEtnia(Character etnia) {
        this.etnia = etnia;
    }    
       
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCedPasaporte() {
        return this.cedPasaporte;
    }
    
    public void setCedPasaporte(String cedPasaporte) {
        this.cedPasaporte = cedPasaporte;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Character getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getPaisOrigen() {
        return this.paisOrigen;
    }
    
    public void setPaisOrigen(String paisOrigen) {
        this.paisOrigen = paisOrigen;
    }
    public Integer getDscColegiatura() {
        return this.dscColegiatura;
    }
    
    public void setDscColegiatura(Integer dscColegiatura) {
        this.dscColegiatura = dscColegiatura;
    }
    public Set getDatosDoms() {
        return this.datosDoms;
    }
    
    public void setDatosDoms(Set datosDoms) {
        this.datosDoms = datosDoms;
    }
    public Set getDatosNacs() {
        return this.datosNacs;
    }
    
    public void setDatosNacs(Set datosNacs) {
        this.datosNacs = datosNacs;
    }
    public Set getDatosLabs() {
        return this.datosLabs;
    }
    
    public void setDatosLabs(Set datosLabs) {
        this.datosLabs = datosLabs;
    }
    public Set getSolicitudInscripcions() {
        return this.solicitudInscripcions;
    }
    
    public void setSolicitudInscripcions(Set solicitudInscripcions) {
        this.solicitudInscripcions = solicitudInscripcions;
    }




}


