package Pojo;
// Generated 28-oct-2016 20:56:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int id;
     private String cedPasaporte;
     private String nombres;
     private String apellidos;
     private String email;
     private String celular;
     private Date fechaNac;
     private Character sexo;
     private Character estadoCivil;
     private String paisOrigen;
     private Integer dscColegiatura;
     private Character etniaId;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private Set datosDoms = new HashSet(0);
     private Set datosNacs = new HashSet(0);
     private Set titulos = new HashSet(0);
     private Set datosLabs = new HashSet(0);
     private Set solicitudInscripcions = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(int id, String cedPasaporte) {
        this.id = id;
        this.cedPasaporte = cedPasaporte;
    }
    public Estudiante(int id, String cedPasaporte, String nombres, String apellidos, String email, String celular, Date fechaNac, Character sexo, Character estadoCivil, String paisOrigen, Integer dscColegiatura, Character etniaId, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, Set datosDoms, Set datosNacs, Set titulos, Set datosLabs, Set solicitudInscripcions) {
       this.id = id;
       this.cedPasaporte = cedPasaporte;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.celular = celular;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.paisOrigen = paisOrigen;
       this.dscColegiatura = dscColegiatura;
       this.etniaId = etniaId;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.datosDoms = datosDoms;
       this.datosNacs = datosNacs;
       this.titulos = titulos;
       this.datosLabs = datosLabs;
       this.solicitudInscripcions = solicitudInscripcions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCedPasaporte() {
        return this.cedPasaporte;
    }
    
    public void setCedPasaporte(String cedPasaporte) {
        this.cedPasaporte = cedPasaporte;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Character getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getPaisOrigen() {
        return this.paisOrigen;
    }
    
    public void setPaisOrigen(String paisOrigen) {
        this.paisOrigen = paisOrigen;
    }
    public Integer getDscColegiatura() {
        return this.dscColegiatura;
    }
    
    public void setDscColegiatura(Integer dscColegiatura) {
        this.dscColegiatura = dscColegiatura;
    }
    public Character getEtniaId() {
        return this.etniaId;
    }
    
    public void setEtniaId(Character etniaId) {
        this.etniaId = etniaId;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public Set getDatosDoms() {
        return this.datosDoms;
    }
    
    public void setDatosDoms(Set datosDoms) {
        this.datosDoms = datosDoms;
    }
    public Set getDatosNacs() {
        return this.datosNacs;
    }
    
    public void setDatosNacs(Set datosNacs) {
        this.datosNacs = datosNacs;
    }
    public Set getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set titulos) {
        this.titulos = titulos;
    }
    public Set getDatosLabs() {
        return this.datosLabs;
    }
    
    public void setDatosLabs(Set datosLabs) {
        this.datosLabs = datosLabs;
    }
    public Set getSolicitudInscripcions() {
        return this.solicitudInscripcions;
    }
    
    public void setSolicitudInscripcions(Set solicitudInscripcions) {
        this.solicitudInscripcions = solicitudInscripcions;
    }




}


