package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1



/**
 * EstudiosRealizados generated by hbm2java
 */
public class EstudiosRealizados  implements java.io.Serializable {


     private int id;
     private Estudiante estudiante;
     private Titulo titulo;
     private Universidad universidad;

    public EstudiosRealizados() {
    }

	
    public EstudiosRealizados(int id) {
        this.id = id;
    }
    public EstudiosRealizados(int id, Estudiante estudiante, Titulo titulo, Universidad universidad) {
       this.id = id;
       this.estudiante = estudiante;
       this.titulo = titulo;
       this.universidad = universidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Titulo getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(Titulo titulo) {
        this.titulo = titulo;
    }
    public Universidad getUniversidad() {
        return this.universidad;
    }
    
    public void setUniversidad(Universidad universidad) {
        this.universidad = universidad;
    }




}


