package Pojo;
// Generated 28-oct-2016 20:56:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * HorarioModulo generated by hbm2java
 */
public class HorarioModulo  implements java.io.Serializable {


     private int id;
     private Modulo modulo;
     private Date horaInicio;
     private Date horaFin;
     private Date fecha;
     private Integer mes;
     private Character dia;
     private BigDecimal hora;
     private Character estado;

    public HorarioModulo() {
    }

	
    public HorarioModulo(int id) {
        this.id = id;
    }
    public HorarioModulo(int id, Modulo modulo, Date horaInicio, Date horaFin, Date fecha, Integer mes, Character dia, BigDecimal hora, Character estado) {
       this.id = id;
       this.modulo = modulo;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
       this.fecha = fecha;
       this.mes = mes;
       this.dia = dia;
       this.hora = hora;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Modulo getModulo() {
        return this.modulo;
    }
    
    public void setModulo(Modulo modulo) {
        this.modulo = modulo;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Character getDia() {
        return this.dia;
    }
    
    public void setDia(Character dia) {
        this.dia = dia;
    }
    public BigDecimal getHora() {
        return this.hora;
    }
    
    public void setHora(BigDecimal hora) {
        this.hora = hora;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


