package Pojo;
// Generated 09/04/2016 3:18:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private int id;
     private Promocion promocion;
     private SolicitudInscripcion solicitudInscripcion;
     private int NMatricula;
     private Date fechaMatricula;
     private Integer dscColegiatura;
     private Character estado;
     private Set asistencias = new HashSet(0);
     private Set pagos = new HashSet(0);
     private Set notases = new HashSet(0);

    public Matricula() {
    }

	
    public Matricula(int id, Promocion promocion, SolicitudInscripcion solicitudInscripcion, int NMatricula) {
        this.id = id;
        this.promocion = promocion;
        this.solicitudInscripcion = solicitudInscripcion;
        this.NMatricula = NMatricula;
    }
    public Matricula(int id, Promocion promocion, SolicitudInscripcion solicitudInscripcion, int NMatricula, Date fechaMatricula, Integer dscColegiatura, Character estado, Set asistencias, Set pagos, Set notases) {
       this.id = id;
       this.promocion = promocion;
       this.solicitudInscripcion = solicitudInscripcion;
       this.NMatricula = NMatricula;
       this.fechaMatricula = fechaMatricula;
       this.dscColegiatura = dscColegiatura;
       this.estado = estado;
       this.asistencias = asistencias;
       this.pagos = pagos;
       this.notases = notases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }
    public SolicitudInscripcion getSolicitudInscripcion() {
        return this.solicitudInscripcion;
    }
    
    public void setSolicitudInscripcion(SolicitudInscripcion solicitudInscripcion) {
        this.solicitudInscripcion = solicitudInscripcion;
    }
    public int getNMatricula() {
        return this.NMatricula;
    }
    
    public void setNMatricula(int NMatricula) {
        this.NMatricula = NMatricula;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public Integer getDscColegiatura() {
        return this.dscColegiatura;
    }
    
    public void setDscColegiatura(Integer dscColegiatura) {
        this.dscColegiatura = dscColegiatura;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


