package Pojo;
// Generated 21-nov-2016 21:32:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int id;
     private Curso curso;
     private Materias materias;
     private Promocion promocion;
     private Usuario usuario;
     private BigDecimal creditos;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private String modulo;
     private Date fechaInicioExamen;
     private Date fechaFinExamen;
     private BigDecimal totalHorasModulo;
     private Character estado;
     private Set horarioModulos = new HashSet(0);
     private Set asistencias = new HashSet(0);
     private Set notases = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int id, Curso curso, Materias materias, Promocion promocion, Usuario usuario) {
        this.id = id;
        this.curso = curso;
        this.materias = materias;
        this.promocion = promocion;
        this.usuario = usuario;
    }
    public Modulo(int id, Curso curso, Materias materias, Promocion promocion, Usuario usuario, BigDecimal creditos, String descripcion, Date fechaInicio, Date fechaFin, String modulo, Date fechaInicioExamen, Date fechaFinExamen, BigDecimal totalHorasModulo, Character estado, Set horarioModulos, Set asistencias, Set notases) {
       this.id = id;
       this.curso = curso;
       this.materias = materias;
       this.promocion = promocion;
       this.usuario = usuario;
       this.creditos = creditos;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.modulo = modulo;
       this.fechaInicioExamen = fechaInicioExamen;
       this.fechaFinExamen = fechaFinExamen;
       this.totalHorasModulo = totalHorasModulo;
       this.estado = estado;
       this.horarioModulos = horarioModulos;
       this.asistencias = asistencias;
       this.notases = notases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Materias getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(Materias materias) {
        this.materias = materias;
    }
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }
    public Date getFechaInicioExamen() {
        return this.fechaInicioExamen;
    }
    
    public void setFechaInicioExamen(Date fechaInicioExamen) {
        this.fechaInicioExamen = fechaInicioExamen;
    }
    public Date getFechaFinExamen() {
        return this.fechaFinExamen;
    }
    
    public void setFechaFinExamen(Date fechaFinExamen) {
        this.fechaFinExamen = fechaFinExamen;
    }
    public BigDecimal getTotalHorasModulo() {
        return this.totalHorasModulo;
    }
    
    public void setTotalHorasModulo(BigDecimal totalHorasModulo) {
        this.totalHorasModulo = totalHorasModulo;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getHorarioModulos() {
        return this.horarioModulos;
    }
    
    public void setHorarioModulos(Set horarioModulos) {
        this.horarioModulos = horarioModulos;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


