package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int id;
     private Matricula matricula;
     private TipoPago tipoPago;
     private Double valor;
     private Date fecha;
     private String idComprobante;
     private String rutaComprobante;

    public Pago() {
    }

	
    public Pago(int id, Matricula matricula, TipoPago tipoPago) {
        this.id = id;
        this.matricula = matricula;
        this.tipoPago = tipoPago;
    }
    public Pago(int id, Matricula matricula, TipoPago tipoPago, Double valor, Date fecha, String idComprobante, String rutaComprobante) {
       this.id = id;
       this.matricula = matricula;
       this.tipoPago = tipoPago;
       this.valor = valor;
       this.fecha = fecha;
       this.idComprobante = idComprobante;
       this.rutaComprobante = rutaComprobante;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getIdComprobante() {
        return this.idComprobante;
    }
    
    public void setIdComprobante(String idComprobante) {
        this.idComprobante = idComprobante;
    }
    public String getRutaComprobante() {
        return this.rutaComprobante;
    }
    
    public void setRutaComprobante(String rutaComprobante) {
        this.rutaComprobante = rutaComprobante;
    }




}


