package Pojo;
// Generated 11/04/2016 15:34:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set universidads = new HashSet(0);
     private Set provincias = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int id) {
        this.id = id;
    }
    public Pais(int id, String descripcion, Set universidads, Set provincias) {
       this.id = id;
       this.descripcion = descripcion;
       this.universidads = universidads;
       this.provincias = provincias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUniversidads() {
        return this.universidads;
    }
    
    public void setUniversidads(Set universidads) {
        this.universidads = universidads;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


