package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private String codigoLetra;
     private Integer codigo;
     private Set universidads = new HashSet(0);
     private Set provincias = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int id) {
        this.id = id;
    }
    public Pais(int id, String descripcion, String codigoLetra, Set universidads, Set provincias, Integer codigo) {
       this.id = id;
       this.descripcion = descripcion;
       this.codigoLetra = codigoLetra;
       this.universidads = universidads;
       this.provincias = provincias;
       this.codigo = codigo;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigoLetra() {
        return this.codigoLetra;
    }
    
    public void setCodigoLetra(String codigoLetra) {
        this.codigoLetra = codigoLetra;
    }
    public Set getUniversidads() {
        return this.universidads;
    }
    
    public void setUniversidads(Set universidads) {
        this.universidads = universidads;
    }
    public Set getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Set provincias) {
        this.provincias = provincias;
    }




}


