package Pojo;
// Generated 30-oct-2016 21:58:04 by Hibernate Tools 4.3.1



/**
 * PalabrasClave generated by hbm2java
 */
public class PalabrasClave  implements java.io.Serializable {


     private int id;
     private Proyecto proyecto;
     private String descripcion;
     private Character estado;

    public PalabrasClave() {
    }

	
    public PalabrasClave(int id, Proyecto proyecto) {
        this.id = id;
        this.proyecto = proyecto;
    }
    public PalabrasClave(int id, Proyecto proyecto, String descripcion, Character estado) {
       this.id = id;
       this.proyecto = proyecto;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }




}


