package Pojo;
// Generated 11/04/2016 15:34:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parroquia generated by hbm2java
 */
public class Parroquia  implements java.io.Serializable {


     private int id;
     private Canton canton;
     private String descripcion;
     private String codigo;
     private Set datosNacs = new HashSet(0);
     private Set datosDoms = new HashSet(0);
     private Set datosLabs = new HashSet(0);

    public Parroquia() {
    }

	
    public Parroquia(int id, Canton canton) {
        this.id = id;
        this.canton = canton;
    }
    public Parroquia(int id, Canton canton, String descripcion, String codigo, Set datosNacs, Set datosDoms, Set datosLabs) {
       this.id = id;
       this.canton = canton;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.datosNacs = datosNacs;
       this.datosDoms = datosDoms;
       this.datosLabs = datosLabs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Canton getCanton() {
        return this.canton;
    }
    
    public void setCanton(Canton canton) {
        this.canton = canton;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getDatosNacs() {
        return this.datosNacs;
    }
    
    public void setDatosNacs(Set datosNacs) {
        this.datosNacs = datosNacs;
    }
    public Set getDatosDoms() {
        return this.datosDoms;
    }
    
    public void setDatosDoms(Set datosDoms) {
        this.datosDoms = datosDoms;
    }
    public Set getDatosLabs() {
        return this.datosLabs;
    }
    
    public void setDatosLabs(Set datosLabs) {
        this.datosLabs = datosLabs;
    }




}


