package Pojo;
// Generated 21-nov-2016 21:32:12 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Ponderaciones generated by hbm2java
 */
public class Ponderaciones  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private BigDecimal ponderacion;
     private Character estado;
     private Integer clave;
     private Set ponderacionFechas = new HashSet(0);

    public Ponderaciones() {
    }

	
    public Ponderaciones(int id) {
        this.id = id;
    }
    public Ponderaciones(int id, String descripcion, BigDecimal ponderacion, Character estado, Integer clave, Set ponderacionFechas) {
       this.id = id;
       this.descripcion = descripcion;
       this.ponderacion = ponderacion;
       this.estado = estado;
       this.clave = clave;
       this.ponderacionFechas = ponderacionFechas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPonderacion() {
        return this.ponderacion;
    }
    
    public void setPonderacion(BigDecimal ponderacion) {
        this.ponderacion = ponderacion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Integer getClave() {
        return this.clave;
    }
    
    public void setClave(Integer clave) {
        this.clave = clave;
    }
    public Set getPonderacionFechas() {
        return this.ponderacionFechas;
    }
    
    public void setPonderacionFechas(Set ponderacionFechas) {
        this.ponderacionFechas = ponderacionFechas;
    }




}


