package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1



/**
 * Postgrado generated by hbm2java
 */
public class Postgrado  implements java.io.Serializable {


     private int id;
     private String email;
     private String claveEmail;
     private int numMatricula;

    public Postgrado() {
    }

	
    public Postgrado(int id) {
        this.id = id;
    }
    public Postgrado(int id, String email, String claveEmail,int numMatricula) {
       this.id = id;
       this.email = email;
       this.claveEmail = claveEmail;
       this.numMatricula=numMatricula;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getClaveEmail() {
        return this.claveEmail;
    }
    
    public void setClaveEmail(String claveEmail) {
        this.claveEmail = claveEmail;
    }

    public int getNumMatricula() {
        return numMatricula;
    }

    public void setNumMatricula(int numMatricula) {
        this.numMatricula = numMatricula;
    }




}


