package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Precio generated by hbm2java
 */
public class Precio  implements java.io.Serializable {


     private int id;
     private Promocion promocion;
     private TipoPrecio tipoPrecio;
     private BigDecimal valor;
     private Date fechaInicio;
     private Date fechaFin;

    public Precio() {
    }

	
    public Precio(int id, Promocion promocion, TipoPrecio tipoPrecio) {
        this.id = id;
        this.promocion = promocion;
        this.tipoPrecio = tipoPrecio;
    }
    public Precio(int id, Promocion promocion, TipoPrecio tipoPrecio, BigDecimal valor, Date fechaInicio, Date fechaFin) {
       this.id = id;
       this.promocion = promocion;
       this.tipoPrecio = tipoPrecio;
       this.valor = valor;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }
    public TipoPrecio getTipoPrecio() {
        return this.tipoPrecio;
    }
    
    public void setTipoPrecio(TipoPrecio tipoPrecio) {
        this.tipoPrecio = tipoPrecio;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


