package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promocion generated by hbm2java
 */
public class Promocion  implements java.io.Serializable {


     private int id;
     private Maestria maestria;
     private Integer descripcion;
     private Date fechaResolucion;
     private Date fechaInicio;
     private Date fechaFin;
     private Integer cupo;
     private Integer NCuotas;
     private int idUsuario;
     private String usuarios;
     private Set precios = new HashSet(0);
     private Set matriculas = new HashSet(0);
     private Set modulos = new HashSet(0);

    public Promocion() {
    }

	
    public Promocion(int id, Maestria maestria, int idUsuario) {
        this.id = id;
        this.maestria = maestria;
        this.idUsuario = idUsuario;
    }
    public Promocion(int id, Maestria maestria, Integer descripcion, Date fechaResolucion, Date fechaInicio, Date fechaFin, Integer cupo, Integer NCuotas, int idUsuario, String usuarios, Set precios, Set matriculas, Set modulos) {
       this.id = id;
       this.maestria = maestria;
       this.descripcion = descripcion;
       this.fechaResolucion = fechaResolucion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.cupo = cupo;
       this.NCuotas = NCuotas;
       this.idUsuario = idUsuario;
       this.precios = precios;
       this.matriculas = matriculas;
       this.modulos = modulos;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Maestria getMaestria() {
        return this.maestria;
    }
    
    public void setMaestria(Maestria maestria) {
        this.maestria = maestria;
    }
    public Integer getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(Integer descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaResolucion() {
        return this.fechaResolucion;
    }
    
    public void setFechaResolucion(Date fechaResolucion) {
        this.fechaResolucion = fechaResolucion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }
    public Integer getNCuotas() {
        return this.NCuotas;
    }
    
    public void setNCuotas(Integer NCuotas) {
        this.NCuotas = NCuotas;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Set getPrecios() {
        return this.precios;
    }
    
    public void setPrecios(Set precios) {
        this.precios = precios;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }

    public String getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(String usuarios) {
        this.usuarios = usuarios;
    }

}


