package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private int id;
     private Pais pais;
     private String descripcion;
     private String codigo;
     private Set cantons = new HashSet(0);

    public Provincia() {
    }

	
    public Provincia(int id, Pais pais) {
        this.id = id;
        this.pais = pais;
    }
    public Provincia(int id, Pais pais, String descripcion, String codigo, Set cantons) {
       this.id = id;
       this.pais = pais;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.cantons = cantons;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getCantons() {
        return this.cantons;
    }
    
    public void setCantons(Set cantons) {
        this.cantons = cantons;
    }




}


