package Pojo;
// Generated 28-oct-2016 20:56:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int id;
     private Titulacion titulacion;
     private Usuario usuario;
     private String titulo;
     private String autor;
     private Date fechaSustentacion;
     private String ruta;
     private String resumen;
     private Date fechaSubida;
     private String maestria;
     private String tutor;
     private Character estado;
     private Set palabrasClaves = new HashSet(0);
     private Set sustentacions = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(int id) {
        this.id = id;
    }
    public Proyecto(int id, Titulacion titulacion, Usuario usuario, String titulo, String autor, Date fechaSustentacion, String ruta, String resumen, Date fechaSubida, String maestria, String tutor, Character estado, Set palabrasClaves, Set sustentacions) {
       this.id = id;
       this.titulacion = titulacion;
       this.usuario = usuario;
       this.titulo = titulo;
       this.autor = autor;
       this.fechaSustentacion = fechaSustentacion;
       this.ruta = ruta;
       this.resumen = resumen;
       this.fechaSubida = fechaSubida;
       this.maestria = maestria;
       this.tutor = tutor;
       this.estado = estado;
       this.palabrasClaves = palabrasClaves;
       this.sustentacions = sustentacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Titulacion getTitulacion() {
        return this.titulacion;
    }
    
    public void setTitulacion(Titulacion titulacion) {
        this.titulacion = titulacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Date getFechaSustentacion() {
        return this.fechaSustentacion;
    }
    
    public void setFechaSustentacion(Date fechaSustentacion) {
        this.fechaSustentacion = fechaSustentacion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }
    public Date getFechaSubida() {
        return this.fechaSubida;
    }
    
    public void setFechaSubida(Date fechaSubida) {
        this.fechaSubida = fechaSubida;
    }
    public String getMaestria() {
        return this.maestria;
    }
    
    public void setMaestria(String maestria) {
        this.maestria = maestria;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getPalabrasClaves() {
        return this.palabrasClaves;
    }
    
    public void setPalabrasClaves(Set palabrasClaves) {
        this.palabrasClaves = palabrasClaves;
    }
    public Set getSustentacions() {
        return this.sustentacions;
    }
    
    public void setSustentacions(Set sustentacions) {
        this.sustentacions = sustentacions;
    }




}


