package Pojo;
// Generated 16-may-2016 9:34:07 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int id;
     private Titulacion titulacion;
     private String titulo;
     private String autor;
     private Date fechaSustentacion;
     private String ruta;
     private String resumen;
     private Date fechaSubida;
     private String maestria;
     private Set palabrasClaves = new HashSet(0);
     private Set sustentacions = new HashSet(0);
     
     private Usuario usuario;
     private String tutor;
     private Boolean estado;

    public Proyecto() {
    }

	
    public Proyecto(int id) {
        this.id = id;
    }
        
    public Proyecto(int id, Titulacion titulacion, String titulo, String autor, Date fechaSustentacion, String ruta, String resumen, Date fechaSubida, String maestria, Usuario usuario, String tutor, Boolean estado,Set palabrasClaves, Set sustentacions) {
        this.id = id;
        this.titulacion = titulacion;
        this.titulo = titulo;
        this.autor = autor;
        this.fechaSustentacion = fechaSustentacion;
        this.ruta = ruta;
        this.resumen = resumen;
        this.fechaSubida = fechaSubida;
        this.maestria = maestria;
        this.usuario = usuario;
        this.tutor = tutor;
        this.estado = estado;
        this.sustentacions=sustentacions;
        this.palabrasClaves=palabrasClaves;
    }
   
   
    
    
    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public String getTutor() {
        return tutor;
    }

    public void setTutor(String tutor) {
        this.tutor = tutor;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Titulacion getTitulacion() {
        return this.titulacion;
    }
    
    public void setTitulacion(Titulacion titulacion) {
        this.titulacion = titulacion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Date getFechaSustentacion() {
        return this.fechaSustentacion;
    }
    
    public void setFechaSustentacion(Date fechaSustentacion) {
        this.fechaSustentacion = fechaSustentacion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }
    public Date getFechaSubida() {
        return this.fechaSubida;
    }
    
    public void setFechaSubida(Date fechaSubida) {
        this.fechaSubida = fechaSubida;
    }
    public String getMaestria() {
        return this.maestria;
    }
    
    public void setMaestria(String maestria) {
        this.maestria = maestria;
    }
    public Set getPalabrasClaves() {
        return this.palabrasClaves;
    }
    
    public void setPalabrasClaves(Set palabrasClaves) {
        this.palabrasClaves = palabrasClaves;
    }
    public Set getSustentacions() {
        return this.sustentacions;
    }
    
    public void setSustentacions(Set sustentacions) {
        this.sustentacions = sustentacions;
    }




}


