package Pojo;
// Generated 11/04/2016 15:34:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Requisitos generated by hbm2java
 */
public class Requisitos  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Character estado;
     private Character respaldo;
     private Set requisitosPromos = new HashSet(0);

    public Requisitos() {
    }

	
    public Requisitos(int id) {
        this.id = id;
    }
    public Requisitos(int id, String descripcion, Character estado, Character respaldo, Set requisitosPromos) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.respaldo = respaldo;
       this.requisitosPromos = requisitosPromos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Character getRespaldo() {
        return this.respaldo;
    }
    
    public void setRespaldo(Character respaldo) {
        this.respaldo = respaldo;
    }
    public Set getRequisitosPromos() {
        return this.requisitosPromos;
    }
    
    public void setRequisitosPromos(Set requisitosPromos) {
        this.requisitosPromos = requisitosPromos;
    }




}


