package Pojo;
// Generated 09/04/2016 3:18:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RequisitosPromo generated by hbm2java
 */
public class RequisitosPromo  implements java.io.Serializable {


     private int id;
     private Promocion promocion;
     private Requisitos requisitos;
     private Character estado;
     private Set archivoses = new HashSet(0);

    public RequisitosPromo() {
    }

	
    public RequisitosPromo(int id, Promocion promocion, Requisitos requisitos) {
        this.id = id;
        this.promocion = promocion;
        this.requisitos = requisitos;
    }
    public RequisitosPromo(int id, Promocion promocion, Requisitos requisitos, Character estado, Set archivoses) {
       this.id = id;
       this.promocion = promocion;
       this.requisitos = requisitos;
       this.estado = estado;
       this.archivoses = archivoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }
    public Requisitos getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(Requisitos requisitos) {
        this.requisitos = requisitos;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getArchivoses() {
        return this.archivoses;
    }
    
    public void setArchivoses(Set archivoses) {
        this.archivoses = archivoses;
    }




}


