package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1



/**
 * Requisitos generated by hbm2java
 */
public class Requisitos  implements java.io.Serializable {


     private int id;
     private Maestria maestria;
     private String descripcion;
     private Character estado;
     private Character respaldo;

    public Requisitos() {
    }

	
    public Requisitos(int id, Maestria maestria) {
        this.id = id;
        this.maestria = maestria;
    }
    public Requisitos(int id, Maestria maestria, String descripcion, Character estado, Character respaldo) {
       this.id = id;
       this.maestria = maestria;
       this.descripcion = descripcion;
       this.estado = estado;
       this.respaldo = respaldo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Maestria getMaestria() {
        return this.maestria;
    }
    
    public void setMaestria(Maestria maestria) {
        this.maestria = maestria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Character getRespaldo() {
        return this.respaldo;
    }
    
    public void setRespaldo(Character respaldo) {
        this.respaldo = respaldo;
    }




}


