package Pojo;
// Generated 28-oct-2016 20:56:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set cursos = new HashSet(0);

    public Seccion() {
    }

	
    public Seccion(int id) {
        this.id = id;
    }
    public Seccion(int id, String descripcion, Set cursos) {
       this.id = id;
       this.descripcion = descripcion;
       this.cursos = cursos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


