package Pojo;
// Generated 11/04/2016 15:34:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tesis generated by hbm2java
 */
public class Tesis  implements java.io.Serializable {


     private int id;
     private Estudiante estudiante;
     private Maestria maestria;
     private String titulo;
     private String autor;
     private Date fechaSustentacion;
     private String ruta;
     private String resumen;
     private Date fechaSubida;
     private Set palabrasClaves = new HashSet(0);

    public Tesis() {
    }

	
    public Tesis(int id, Maestria maestria) {
        this.id = id;
        this.maestria = maestria;
    }
    public Tesis(int id, Estudiante estudiante, Maestria maestria, String titulo, String autor, Date fechaSustentacion, String ruta, String resumen, Date fechaSubida, Set palabrasClaves) {
       this.id = id;
       this.estudiante = estudiante;
       this.maestria = maestria;
       this.titulo = titulo;
       this.autor = autor;
       this.fechaSustentacion = fechaSustentacion;
       this.ruta = ruta;
       this.resumen = resumen;
       this.fechaSubida = fechaSubida;
       this.palabrasClaves = palabrasClaves;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Maestria getMaestria() {
        return this.maestria;
    }
    
    public void setMaestria(Maestria maestria) {
        this.maestria = maestria;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Date getFechaSustentacion() {
        return this.fechaSustentacion;
    }
    
    public void setFechaSustentacion(Date fechaSustentacion) {
        this.fechaSustentacion = fechaSustentacion;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }
    public Date getFechaSubida() {
        return this.fechaSubida;
    }
    
    public void setFechaSubida(Date fechaSubida) {
        this.fechaSubida = fechaSubida;
    }
    public Set getPalabrasClaves() {
        return this.palabrasClaves;
    }
    
    public void setPalabrasClaves(Set palabrasClaves) {
        this.palabrasClaves = palabrasClaves;
    }




}


