package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tesis generated by hbm2java
 */
public class Tesis  implements java.io.Serializable {


     private int id;
     private Maestria maestria;
     private String titulo;
     private String autor;
     private Date fecha;
     private String ruta;
     private String resumen;
     private Set palabrasClaves = new HashSet(0);

    public Tesis() {
    }

	
    public Tesis(int id, Maestria maestria) {
        this.id = id;
        this.maestria = maestria;
    }
    public Tesis(int id, Maestria maestria, String titulo, String autor, Date fecha, String ruta, String resumen, Set palabrasClaves) {
       this.id = id;
       this.maestria = maestria;
       this.titulo = titulo;
       this.autor = autor;
       this.fecha = fecha;
       this.ruta = ruta;
       this.resumen = resumen;
       this.palabrasClaves = palabrasClaves;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Maestria getMaestria() {
        return this.maestria;
    }
    
    public void setMaestria(Maestria maestria) {
        this.maestria = maestria;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }
    public Set getPalabrasClaves() {
        return this.palabrasClaves;
    }
    
    public void setPalabrasClaves(Set palabrasClaves) {
        this.palabrasClaves = palabrasClaves;
    }




}


