package Pojo;
// Generated 11/04/2016 15:34:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTribunal generated by hbm2java
 */
public class TipoTribunal  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set detalleTribunals = new HashSet(0);

    public TipoTribunal() {
    }

	
    public TipoTribunal(int id) {
        this.id = id;
    }
    public TipoTribunal(int id, String descripcion, Set detalleTribunals) {
       this.id = id;
       this.descripcion = descripcion;
       this.detalleTribunals = detalleTribunals;
    }

    public TipoTribunal(int i, String ninguno) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getDetalleTribunals() {
        return this.detalleTribunals;
    }
    
    public void setDetalleTribunals(Set detalleTribunals) {
        this.detalleTribunals = detalleTribunals;
    }




}


