package Pojo;
// Generated 21-nov-2016 21:32:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTribunal generated by hbm2java
 */
public class TipoTribunal  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Character estado;
     private Set tribunals = new HashSet(0);

    public TipoTribunal() {
    }

	
    public TipoTribunal(int id) {
        this.id = id;
    }
    public TipoTribunal(int id, String descripcion, Character estado, Set tribunals) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.tribunals = tribunals;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getTribunals() {
        return this.tribunals;
    }
    
    public void setTribunals(Set tribunals) {
        this.tribunals = tribunals;
    }




}


