package Pojo;
// Generated 02-nov-2016 10:39:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoTitulacion generated by hbm2java
 */
public class TipoTitulacion  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Character estado;
     private Set titulacions = new HashSet(0);

    public TipoTitulacion() {
    }

	
    public TipoTitulacion(int id) {
        this.id = id;
    }
    public TipoTitulacion(int id, String descripcion, Character estado, Set titulacions) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.titulacions = titulacions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set getTitulacions() {
        return this.titulacions;
    }
    
    public void setTitulacions(Set titulacions) {
        this.titulacions = titulacions;
    }




}


