package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Titulo generated by hbm2java
 */
public class Titulo  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private String NSenecyt;
     private Set estudiosRealizadoses = new HashSet(0);

    public Titulo() {
    }

	
    public Titulo(int id) {
        this.id = id;
    }
    public Titulo(int id, String descripcion, String NSenecyt, Set estudiosRealizadoses) {
       this.id = id;
       this.descripcion = descripcion;
       this.NSenecyt = NSenecyt;
       this.estudiosRealizadoses = estudiosRealizadoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNSenecyt() {
        return this.NSenecyt;
    }
    
    public void setNSenecyt(String NSenecyt) {
        this.NSenecyt = NSenecyt;
    }
    public Set getEstudiosRealizadoses() {
        return this.estudiosRealizadoses;
    }
    
    public void setEstudiosRealizadoses(Set estudiosRealizadoses) {
        this.estudiosRealizadoses = estudiosRealizadoses;
    }




}


