package Pojo;
// Generated 09/04/2016 3:18:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tribunal generated by hbm2java
 */
public class Tribunal  implements java.io.Serializable {


     private int id;
     private Date fecha;
     private String nota;
     private Set detalleTribunals = new HashSet(0);

    public Tribunal() {
    }

	
    public Tribunal(int id) {
        this.id = id;
    }
    public Tribunal(int id, Date fecha, String nota, Set detalleTribunals) {
       this.id = id;
       this.fecha = fecha;
       this.nota = nota;
       this.detalleTribunals = detalleTribunals;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public Set getDetalleTribunals() {
        return this.detalleTribunals;
    }
    
    public void setDetalleTribunals(Set detalleTribunals) {
        this.detalleTribunals = detalleTribunals;
    }




}


