package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set estudiosRealizadoses = new HashSet(0);

    public Universidad() {
    }

	
    public Universidad(int id) {
        this.id = id;
    }
    public Universidad(int id, String descripcion, Set estudiosRealizadoses) {
       this.id = id;
       this.descripcion = descripcion;
       this.estudiosRealizadoses = estudiosRealizadoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getEstudiosRealizadoses() {
        return this.estudiosRealizadoses;
    }
    
    public void setEstudiosRealizadoses(Set estudiosRealizadoses) {
        this.estudiosRealizadoses = estudiosRealizadoses;
    }




}


