package Pojo;
// Generated 28-oct-2016 20:56:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Universidad generated by hbm2java
 */
public class Universidad  implements java.io.Serializable {


     private int id;
     private Pais pais;
     private String descripcion;
     private Set titulos = new HashSet(0);

    public Universidad() {
    }

	
    public Universidad(int id, Pais pais) {
        this.id = id;
        this.pais = pais;
    }
    public Universidad(int id, Pais pais, String descripcion, Set titulos) {
       this.id = id;
       this.pais = pais;
       this.descripcion = descripcion;
       this.titulos = titulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTitulos() {
        return this.titulos;
    }
    
    public void setTitulos(Set titulos) {
        this.titulos = titulos;
    }




}


