 package Pojo;
// Generated 29/02/2016 10:09:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private TipoUsuario tipoUsuario;
     private String cedPasaporte;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefono;
     private String email;
     private Character estadoCivil;
     private Character sexo;
     private Date fechaNac;
     private String celular;
     private Character estado;
     private String nick;
     private String clave;
     private String usuarioBd;
     private String claveBd;
     private Set detallePermisos = new HashSet(0);
     private Set modulos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, TipoUsuario tipoUsuario, String cedPasaporte) {
        this.id = id;
        this.tipoUsuario = tipoUsuario;
        this.cedPasaporte = cedPasaporte;
    }
    public Usuario(int id, TipoUsuario tipoUsuario, String cedPasaporte, String nombres, String apellidos, String direccion, String telefono, String email, Character estadoCivil, Character sexo, Date fechaNac, String celular, Character estado, String nick, String clave, String usuarioBd, String claveBd, Set detallePermisos, Set modulos) {
       this.id = id;
       this.tipoUsuario = tipoUsuario;
       this.cedPasaporte = cedPasaporte;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.estadoCivil = estadoCivil;
       this.sexo = sexo;
       this.fechaNac = fechaNac;
       this.celular = celular;
       this.estado = estado;
       this.nick = nick;
       this.clave = clave;
       this.usuarioBd = usuarioBd;
       this.claveBd = claveBd;
       this.detallePermisos = detallePermisos;
       this.modulos = modulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getCedPasaporte() {
        return this.cedPasaporte;
    }
    
    public void setCedPasaporte(String cedPasaporte) {
        this.cedPasaporte = cedPasaporte;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Character getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(Character estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public Character getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public String getNick() {
        return this.nick;
    }
    
    public void setNick(String nick) {
        this.nick = nick;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getUsuarioBd() {
        return this.usuarioBd;
    }
    
    public void setUsuarioBd(String usuarioBd) {
        this.usuarioBd = usuarioBd;
    }
    public String getClaveBd() {
        return this.claveBd;
    }
    
    public void setClaveBd(String claveBd) {
        this.claveBd = claveBd;
    }
    public Set getDetallePermisos() {
        return this.detallePermisos;
    }
    
    public void setDetallePermisos(Set detallePermisos) {
        this.detallePermisos = detallePermisos;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }




}


